env:
  browser: true
  es6: true
  node: true
  es2021: true
extends:
  - airbnb
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
  - 'plugin:import/errors'
  - 'plugin:import/warnings'
  - 'plugin:import/typescript'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  project: ./tsconfig.json
  ecmaVersion: latest
  sourceType: module
plugins:
  - import
  - simple-import-sort
  - unused-imports
  - '@typescript-eslint'
overrides:
  -
    files:
      - "*.ts"
    rules:
      simple-import-sort/imports:
        - error
        -
          groups:
            - 
              - "^@?\\w"
            -
              - "^(@/|assets|data|globals|icons|utils)"
              # Side effect imports.
              - "^\\u0000"
              # Parent imports. Put `..` last.
              - "^\\.\\.(?!/?$)"
              - "^\\.\\./?$"
              # Other relative imports. Put same-folder imports and `.` last.
              - "^\\./(?=.*/)(?!/?$)"
              - "^\\.(?!/?$)"
              - "^\\./?$"
              # Style imports.
              - "^.+\\.s?css$"
rules:
  arrow-body-style:
    - error
    - as-needed
  comma-dangle: 0
  indent:
    - error
    - 2
    - SwitchCase: 1
  max-len:
    - error
    - code: 120
      tabWidth: 2
  no-shadow: 'off'
  no-tabs:
    - error
  no-unused-vars: 'off'
  no-else-return: 'off'
  no-trailing-spaces:
    - error
    - ignoreComments: true
  no-use-before-define: 'off'
  no-duplicate-imports:
    - error
    - includeExports: true
  semi:
    - error
    - never
  object-curly-spacing:
    - error
    - always
    - arraysInObjects: true
      objectsInObjects: true
  padded-blocks: 0
  vars-on-top: error
  import/no-commonjs: 2
  import/no-unresolved: 'off'
  import/order: 'off'
  import/extensions:
    - 1
    - never
  import/prefer-default-export: 2
  import/no-extraneous-dependencies: 0
  simple-import-sort/imports: error
  simple-import-sort/exports: error
  unused-imports/no-unused-imports-ts: error
  '@typescript-eslint/no-shadow':
    - error
  '@typescript-eslint/no-unused-vars':
    - error
    - vars: all
      args: after-used
      ignoreRestSiblings: false
settings:
  import/resolver:
    typescript: {}
